#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

set -e

$DIR/commit-auto

PROMPT="${@}"

codex exec \
 --full-auto \
 --sandbox workspace-write \
 "$PROMPT"

$DIR/commit-auto