#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PROMPT="${@}"

TASK_ID="codex-task-$(date +%Y%m%d-%H%M%S)-$$"
LOG_FILE=$PWD/.codex-task/$TASK_ID.log
RESULT_FILE=$PWD/.codex-task/$TASK_ID.RESULT.log

mkdir -p "$PWD/.codex-task"
screen -S "$TASK_ID" -L -Logfile "$LOG_FILE" -dm bash -lc "$DIR/codex-task-fg $PROMPT. Всю иформацию о результатах выполнения задачи или ответ на вопрос запиши в файл $RESULT_FILE"
screen -r $TASK_ID
cat $RESULT_FILE