#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PROMPT_FILE="${@}"

PROJECTS_DIR=$HOME/projects

TASK_ID="codex-task-$(date +%Y%m%d-%H%M%S)-$$"
LOG_FILE=$DIR/.codex-task/logs/$TASK_ID.log
RESULT_FILE=$DIR/.codex-task/logs/$TASK_ID.RESULT.log

PROMPT_FILE=$DIR/tasks/$PROMPT_FILE.md
AGENTS_FILE=$DIR/AGENTS.md

if [ ! -f "$PROMPT_FILE" ]; then
    echo "File does not exist: $PROMPT_FILE"
    exit 1
fi

POST_PROMPT_1="В качестве базовой шпаргалки используй информацию из AGENTS-файла $AGENTS_FILE: там даны общие рекомендации по типовым задачам, подходам и паттернам"
POST_PROMPT_2="Всю иформацию о результатах выполнения задачи или ответ на вопрос запиши в файл $RESULT_FILE"

PROMPT="Ты Senior Backend Developer / Software Engineer. Текст задания прочитай в файле: $PROMPT_FILE, содержимое файла считай своим промптом"

cd "$PROJECTS_DIR"

codex exec \
 --full-auto \
 --skip-git-repo-check \
 --sandbox workspace-write \
 "$PROMPT. $POST_PROMPT_1. $POST_PROMPT_2"

$DIR/push-all
cat "$RESULT_FILE"