#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PROMPT="${@}"

TASK_ID="codex-task-$(date +%Y%m%d-%H%M%S)-$$"
LOG_FILE=$PWD/.codex-task/$TASK_ID.log
RESULT_FILE=$PWD/.codex-task/$TASK_ID.RESULT.log

POST_PROMPT_1="Не делай вызовов go test, они пока не работают, решай проблему без запуска тестов"
POST_PROMPT_2="Всю иформацию о результатах выполнения задачи или ответ на вопрос запиши в файл $RESULT_FILE"

mkdir -p "$PWD/.codex-task"
screen -S "$TASK_ID" -L -Logfile "$LOG_FILE" -dm bash -lc "$DIR/codex-task-fg $PROMPT. $POST_PROMPT_1. $POST_PROMPT_2"
screen -r $TASK_ID
cat $RESULT_FILE