#!/bin/bash

set -e

function doTask {
    projectName=$1
    cd /home/glex/projects/$projectName
    codex-task-f-global redis-cluster
    lint-fix
    push
}

function doBilling {
    cd /home/glex/projects/br-billing
    codex-task-f-global redis-cluster
    push
}

doTask br-users
doTask br-kyc
doTask br-partnership
doTask br-trading
doTask br-support
doTask br-accounts

doBilling